---
id: sinatrasapporo-20150919
base_name: sinatra-with-bower
tags:
- rabbit
- sinatra
- javascript
presentation_date: 2015-09-19
version: 2015.9.19.0
licenses:
- CC BY 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
